### PR TITLE
Update poetry to 1.2.2 and regenerate lockfile

### PR DESCRIPTION
**Pull request by bodograumann**
inboard depends on gunicorn, which in turn depends on setuptools for `pkg_resources`.
Unfortunately this sub-dependency is not mentioned in the `poetry.lock` file.
That means when building a docker file as described in [the docs](https://github.com/br3ndonland/inboard/blob/develop/docs/docker.md#use-images-in-a-dockerfile), `RUN poetry install` will actually uninstall setuptools.
```
   - Removing setuptools (65.4.1)
```

That in turn breaks guincorn.

```
Traceback (most recent call last):
ModuleNotFoundError: No module named 'pkg_resources'
    import pkg_resources
  File "/app/.venv/lib/python3.10/site-packages/gunicorn/util.py", line 25, in <module>
    from gunicorn import util
  File "/app/.venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 11, in <module>
    from gunicorn.app.base import Application
  File "/app/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 9, in <module>
    from gunicorn.app.wsgiapp import run
  File "/app/.venv/bin/gunicorn", line 5, in <module>
```

All I did for this PR is run `poetry lock` in the repository. It added setuptools in line 199 of poetry.lock as well as in the `[metadata.files]` section.

### CODE REVIEW

**Comment by bodograumann** [comment]
Mmh, this might actually be caused by the lock file being written with poetry 1.2, while the inboard base image is still supplying poetry 1.1. Let me try updating that and let's see what happens.
Cf. https://github.com/python-poetry/poetry/issues/6328#issuecomment-1237573933

**Comment by bodograumann** [comment]
Ok, seems like updating poetry does the trick. I have updated the PR title accordingly.

**Comment by bodograumann** [comment]
Thanks for the in-depth response and sorry that I don't have much more time to put in here currently.
I did update poetry in our docker image, so that worked for now. Long term we should find a proper solution though.
You have probably seen that now there is even poetry 1.3 with a completely new lockfile format v2.

I hope I find some time to look into hatch and what you wrote in your comparison with poetry.

**Comment by br3ndonland** [comment]
Sounds great, thanks for reporting back! I closed this off for now, because PR #58 migrated the project to Hatch instead, so there's no `poetry.lock` anymore.

Note that Poetry 1.1 is still installed in the Docker images for backwards compatibility. You can continue using the suggestions I provided in my previous comment (running `pipx upgrade poetry` to upgrade to a newer version of Poetry). You could also use `pipx install poetry>1.2 --force`, which will work whether or not Poetry is already installed by `pipx`. I will eventually have to remove Poetry 1.1 from the Docker containers, because it's no longer maintained, so `pipx install poetry>1.2 --force` is a more future-proof command than `pipx upgrade poetry`.

Thanks again for looking into Poetry 1.2. I would welcome other contributions from you in the future.

**Pull request closed without merging**
